name: CI Workflow

# When the workflow should run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    # Add this section:
    defaults:
      run:
        working-directory: ./my-app

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # This ensures the cache looks in the right place too
          cache: 'npm'
          cache-dependency-path: './my-app/package-lock.json'

      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
